{
 "title": "Somnia Node",
 "time": { "from": "now-8h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "env",
    "query": {
     "query": "label_values(ledger_block_number,env)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ledger_block_number{env=\"$env\"}",
     "legendFormat": "Block Height"
    },
    {
     "expr": "cuthbert_last_executed_block{env=\"$env\"}",
     "legendFormat": "cuthbert"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(ledger_block_number{env=\"$env\"}[5m])",
     "legendFormat": "Block rate"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "in_current_epoch{env=\"$env\"}",
     "legendFormat": "Node Status"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (status) (rate(transaction_statuses{env=\"$env\"}[$__rate_interval]))",
     "legendFormat": "Transaction status per second"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "API requests per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (rpc) (rate(api_requests{env=\"$env\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API errors per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "sum by (rpc, error) (rate(api_errors{env=\"$env\"}[$__rate_interval]))",
     "legendFormat": "{{rpc}}: {{error}}"
    }
   ]
  },
  {
   "title": "API latency (99th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(api_latency_bucket{env=\"$env\"}[$__rate_interval])) by (rpc, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Backend latency (99th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(backend_pipeling_latency_ns_bucket{env=\"$env\"}[$__rate_interval])) by (stage, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Actor queue latency (99th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(actor_input_queue_latency_bucket{env=\"$env\"}[$__rate_interval])) by (name, le))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Internal mean latencies",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum by (stage) (rate(data_chain_latency_counts{env=\"$env\"}[$__rate_interval]))) / on() group_left() sum(rate(data_chain_latency_counts_num_samples{env=\"$env\"}[$__rate_interval]))",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Task active times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(name) (rate(dynamic_consumer_time_cycles{job=\"${job}\", instance=~\"${node}\"}[$__rate_interval]) / on(instance) group_left() rate(cycles_since_start{job=\"${job}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "Avg {{name}}"
    },
    {
     "expr": "avg by(name) (rate(background_task_active_time{job=\"${job}\", instance=~\"${node}\"}[$__rate_interval]) / on(instance) group_left() rate(cycles_since_start{job=\"${job}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "Avg {{name}}"
    },
    {
     "expr": "avg by(name) (1.0 - (rate(event_loop_idle_time_ns{job=\"${job}\", instance=~\"${node}\"}[$__rate_interval]) / 1000000000))",
     "legendFormat": "Avg {{name}}"
    },
    {
     "expr": "avg by(index) (rate(api_dispatcher_shard_active_time{job=\"${job}\", instance=~\"${node}\"}[$__rate_interval]) / on(instance) group_left() rate(cycles_since_start{job=\"${job}\", instance=~\"${node}\"}[$__rate_interval]))",
     "legendFormat": "Avg API {{index}}"
    }
   ]
  },
  {
   "title": "Protocol messages per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "sum by (type) (rate(protocol_egress_messages{env=\"$env\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (type) (rate(protocol_ingress_messages{env=\"$env\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Protocol bytes per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (type) (rate(protocol_egress_bytes{env=\"$env\"}[$__rate_interval]))",
     "legendFormat": "Max Egress: {{type}}"
    },
    {
     "expr": "max by (type) (rate(protocol_ingress_bytes{env=\"$env\"}[$__rate_interval]))",
     "legendFormat": "Max Ingress: {{type}}"
    },
    {
     "expr": "avg by (type) (rate(protocol_egress_bytes{env=\"$env\"}[$__rate_interval]))",
     "legendFormat": "Avg Egress: {{type}}"
    },
    {
     "expr": "avg by (type) (rate(protocol_ingress_bytes{env=\"$env\"}[$__rate_interval]))",
     "legendFormat": "Avg Ingress: {{type}}"
    }
   ]
  },
  { "title": "Consensus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "current_epoch_number{env=\"$env\"}",
     "legendFormat": "Epoch"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(current_epoch_size{env=\"$env\"})",
     "legendFormat": "Epoch size"
    }
   ]
  },
  {
   "title": "PBFT messages per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
   "targets": [
    {
     "expr": "sum by (type) (rate(pbft_sent_messages{env=\"$env\"}[$__rate_interval]))",
     "legendFormat": "Sent: {{type}}"
    },
    {
     "expr": "sum by (type) (rate(pbft_received_messages{env=\"$env\"}[$__rate_interval]))",
     "legendFormat": "Received: {{type}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Info",
     "expr": "(sum by(level) (count_over_time({filename=\"/opt/somnia/log/somnia.log\"} |~ `(?i)inf` [$__auto])) * 100) / sum(count_over_time({filename=\"/opt/somnia/log/somnia.log\"} [$__auto]))",
     "legendFormat": "Info",
     "scenarioId": "INFO"
    },
    {
     "alias": "Error",
     "expr": "(sum by(level) (count_over_time({filename=\"/opt/somnia/log/somnia.log\"} |~ `(?i)err` [$__auto])) * 100) / sum(count_over_time({filename=\"/opt/somnia/log/somnia.log\"} [$__auto]))",
     "legendFormat": "Error",
     "scenarioId": "ERROR"
    },
    {
     "alias": "Debug",
     "expr": "sum by (level) (count_over_time({filename=\"/opt/somnia/log/somnia.log\"} |~  `(?i)deb` [$__auto])) / (sum(count_over_time({filename=\"/opt/somnia/log/somnia.log\"} [$__auto]))) * 100",
     "legendFormat": "Debug",
     "scenarioId": "DEBUG"
    },
    {
     "alias": "Warn",
     "expr": "sum by (level) (count_over_time({filename=\"/opt/somnia/log/somnia.log\"} |~  `(?i)war` [$__auto])) / (sum(count_over_time({filename=\"/opt/somnia/log/somnia.log\"} [$__auto]))) * 100",
     "legendFormat": "Warn",
     "scenarioId": "WARN"
    }
   ]
  },
  {
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=\"/opt/somnia/log/somnia.log\"}"
    }
   ]
  }
 ]
}